### BASIC INTRODUCTION TO NUMPY

Numpy is a python Library for scientific and numeric computation. It provides a high performance multidimensional array object and tools for working with these arrays.

In [1]:
#Import Numpy before use
import numpy as np
%config Completer.use_jedi = False

#### 1-D ARRAYS

These are also called vectors (row or column vectors)

In [2]:
a = [1,2,3,4]

In [3]:
type(a)

list

In [4]:
#create 1 D array in numpy
array_1d = np.array(a)
array_1d

array([1, 2, 3, 4])

In [6]:
array_1d + array_1d

array([2, 4, 6, 8])

#### 2-D ARRAYS

This is also called a matrix

In [7]:
#create 2 D array in numpy
array_2d = np.array([(1,2,3,4), (2,4,6,7)])
array_2d

array([[1, 2, 3, 4],
       [2, 4, 6, 7]])

In [8]:
np.array([[1,2,3,4],[2,4,6,7]])

array([[1, 2, 3, 4],
       [2, 4, 6, 7]])

#### 3-D ARRAYS

In [ ]:
#create 3-D array in numpy
array_3d = np.array([[(20,30,40), (34,45,50), (60,90,43)]])
array_3d

### Initial Placeholders/ Default Arrays

In [9]:
#### Create an array of Zeros
arr_zeros = np.zeros((3,4,5))
arr_zeros

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [15]:
#### Create an array of ones
arr_ones = np.ones((2, 2))
arr_ones

array([[1., 1.],
       [1., 1.]])

In [16]:
list(range(0,20, 2))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [17]:
#### Create an array of evenly spaced values
arr_even = np.arange(0,10, 2)
arr_even

array([0, 2, 4, 6, 8])

In [19]:
#### Create an array of evenly spaced values
arr_line = np.linspace(0,12,5)
arr_line

array([ 0.,  3.,  6.,  9., 12.])

In [23]:
#### Create a constant array
arr_full = np.full((3,6), 6)
arr_full

array([[6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6]])

In [24]:
#### Create a constant array
arr_diag = np.eye(4)
arr_diag

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
#### Create an array with random values
arr_rand = np.random.random((3,3))
arr_rand

array([[0.5554441 , 0.76019889, 0.00741879],
       [0.17394891, 0.95797079, 0.85198762],
       [0.61033343, 0.4497094 , 0.03893822]])

In [27]:
#### Create an empty array
arr_empty = np.empty((3,4))
arr_empty

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Inspecting your Arrays

In [41]:
test_array = np.array([(2,4,5), (5,6,7), (3,4,5), (7,8,7)])
test_array

array([[2, 4, 5],
       [5, 6, 7],
       [3, 4, 5],
       [7, 8, 7]])

In [39]:
# Check the shape
test_array.shape

(3, 3)

In [42]:
#check the length
len(test_array)

4

In [43]:
a = np.array([(2,4,5), (3,4,7)])

In [44]:
a.ndim

2

In [45]:
#Check the dimension of an array
test_array.ndim

2

In [46]:
array_2d.ndim

2

In [47]:
#Check size
test_array.size

12

In [48]:
#Check data types
test_array.dtype

dtype('int32')

In [49]:
#convert an array to a different type
test_array.astype(str)

array([['2', '4', '5'],
       ['5', '6', '7'],
       ['3', '4', '5'],
       ['7', '8', '7']], dtype='<U11')

In [50]:
##3 Asking for Help
np.info(np.ndarray.conjugate)

a.conjugate()

Return the complex conjugate, element-wise.

Refer to `numpy.conjugate` for full documentation.

See Also
--------
numpy.conjugate : equivalent function


### ARRAY MATHEMATICS

In [51]:
arr1 = np.array([1,4,5])
arr2 = np.array([2,3,4])

In [52]:
## ADDITION
arr1 + arr2

array([3, 7, 9])

In [53]:
## SUBTRACTION
arr1 - arr2

array([-1,  1,  1])

In [54]:
np.add(arr1,arr2)

array([3, 7, 9])

In [55]:
## DIVISION
arr1 / arr2

array([0.5       , 1.33333333, 1.25      ])

In [56]:
## MULTIPLICATION
arr1 * arr2

array([ 2, 12, 20])

There are other trig and mathematical functions to try out. Check the documantation at [DOC](https://numpy.org)

### COMPARISON

In [57]:
arr1

array([1, 4, 5])

In [58]:
arr2

array([2, 3, 4])

In [59]:
#Element-Wise Comparison
arr1 == arr2

array([False, False, False])

In [60]:
arr1 < arr2

array([ True, False, False])

### AGGREGATE FUNCTIONS

In [61]:
temp_arr = np.array([[2,3,4], [3,4,6]])
temp_arr

array([[2, 3, 4],
       [3, 4, 6]])

In [62]:
temp_arr.sum()

22

In [63]:
temp_arr.min()

2

In [70]:
temp_arr.max(axis=1)

array([4, 6])

In [72]:
temp_arr.cumsum(axis=0)

array([[ 2,  3,  4],
       [ 5,  7, 10]], dtype=int32)

In [73]:
temp_arr.std()

1.247219128924647

In [74]:
temp_arr.mean()

3.6666666666666665

### COPYING ARRAYS

In [75]:
#Shallow copy | Changes to y_array will affect original array
y_array = temp_arr

In [76]:
temp_arr

array([[2, 3, 4],
       [3, 4, 6]])

In [77]:
y_array[0] = [3,3,3]
y_array

array([[3, 3, 3],
       [3, 4, 6]])

In [78]:
temp_arr

array([[3, 3, 3],
       [3, 4, 6]])

In [79]:
#Deep copy | Changes to new_arr will not affect original array
new_arr = np.copy(temp_arr)
new_arr[0][1] = 2
new_arr

array([[3, 2, 3],
       [3, 4, 6]])

In [80]:
temp_arr

array([[3, 3, 3],
       [3, 4, 6]])

### SLICING, SUBSETTING AND INDEXING

Works like normal list functions

In [81]:
temp_arr

array([[3, 3, 3],
       [3, 4, 6]])

In [82]:
#Subsetting
temp_arr[0]

array([3, 3, 3])

In [83]:
#Slicing

#temp[row : column]

temp_arr[0,1:3]

array([3, 3])

In [85]:
temp_arr[:, 2]

array([3, 6])

In [88]:
#Boolean Indexing

temp_arr[temp_arr == 4]

array([4])

### ARRAY MANIPULATION

In [89]:
temp_arr

array([[3, 3, 3],
       [3, 4, 6]])

In [90]:
#Tranposing
atrans = temp_arr.T
atrans

array([[3, 3],
       [3, 4],
       [3, 6]])

In [91]:
#Change Shape
temp_arr.ravel()  #Flatten Array

array([3, 3, 3, 3, 4, 6])

In [92]:
temp_arr

array([[3, 3, 3],
       [3, 4, 6]])

In [94]:
#Reshape
temp_arr.reshape(-1, 2)

array([[3, 3],
       [3, 3],
       [4, 6]])

In [95]:
#Combining arrays
a = np.array([2,3,4])
b = np.array([4,5,6])

np.concatenate((a,b))

array([2, 3, 4, 4, 5, 6])

In [96]:
#Stack Array Row wise
np.vstack((a,b))

array([[2, 3, 4],
       [4, 5, 6]])

In [97]:
#Stack Array column wise
np.hstack((a,b))

array([2, 3, 4, 4, 5, 6])

In [ ]:
a

In [98]:
#Stack columns
np.column_stack((a,b))

array([[2, 4],
       [3, 5],
       [4, 6]])

### Practice Questions

1. Create an Identitty Matrix of dimension 4-by-4 <hr />

2. Convert all the elements of this numpy array from float to integer datatype

a = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])
              
 <hr />

3. Stack 2 numpy arrays horizontally i.e., 2 arrays having the same 1st dimension (number of rows in 2D arrays) 

tip: 
Dimension = Row by Column

horizontal stacking i.e `hstack()`<hr />


4. Stack 2 numpy arrays vertically i.e., 2 arrays having the same last dimension (number of columns in 2D arrays)<hr />



5. Create a matrix of dimension 2-by-3 with each and every value equal to 5

tip:

you might want to check `numpy.full()`<hr />

6. Output a 3-by-3 array of random numbers following normal distribution  <hr />

7. Output the transpose this matrix 

matr = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])<hr />